[package]
name = "recoverable-errors"
version = "0.1.0"
authors = ["frankhart2018 <siddharthadhar_soumen@srmuniv.edu.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
